import Navbar from "@/components/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter, Open_Sans, Space_Grotesk } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/mode-toggle";

const open = Open_Sans({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "NEXT SPOTIFY API",
  description: "Generated by Harun",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={open.className}>
        {/* <SessionProviders> */}
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="bg-[#00F260]/80 absolute top-[-6rem] -z-10 right-[11rem] h-[31.25rem] w-[31.25rem] rounded-full blur-[10rem] opacity-50 sm:w-[68.75rem] dark:bg-[#946263]"></div>
          <div className="bg-[#C9D6FF] absolute top-[-1rem] -z-10 left-[-35rem] h-[31.25rem] w-[50rem] rounded-full blur-[10rem] sm:w-[68.75rem] md:left-[-33rem] lg:left-[-28rem] xl:left-[-15rem] 2xl:left-[-5rem] dark:bg-[#676394]/50"></div>
          <main className="max-w-7xl mx-auto">
            <Navbar />
            {children}
            <ModeToggle />
          </main>
        </ThemeProvider>
        {/* </SessionProviders> */}
      </body>
    </html>
  );
}
